"""Точка входа для кодо генератора клиентского плагина KBEngine на Python."""

import asyncio
import logging
import os
import shutil
import sys
from typing import TYPE_CHECKING

from environs import Env, EnvError

from enki.command.server_api.importClientEntityDef_cmd import (
    ImportClientEntityDefCommand,
)
from enki.command.server_api.importClientMessages_cmd import (
    ImportClientMessagesCommand,
)
from enki.command.server_api.importServerErrorsDescr_cmd import (
    ImportServerErrorsDescrCommand,
)
from enki.misc import log
from enki.net.addr import Addr, Port
from tools.egenerator import settings
from tools.egenerator.codegen import (
    EntitiesCodeGen,
    EntitySerializersCodeGen,
    ErrorCodeGen,
    KBEngineXMLDataCodeGen,
    MessagesCodeGen,
    TypesCodeGen,
)
from tools.parsers import (
    DefClassData,
    EntitiesXMLParser,
    EntityDefParser,
    KBEngineXMLParser,
)

if TYPE_CHECKING:
    from types import ModuleType

logger = logging.getLogger(__name__)


async def generate_code(
    login_name: str, password: str, loginapp_addr: Addr
) -> None:
    # Parse assets info
    assets_ent_data: dict[str, DefClassData] = {}
    entities_xml_parser: EntitiesXMLParser = EntitiesXMLParser(
        settings.ENTITIES_XML_PATH
    )
    entity_def_parser: EntityDefParser = EntityDefParser(settings.ENTITY_DEFS_DIR)
    for ent_data in entities_xml_parser.parse().get_all():
        assets_ent_data[ent_data.name] = entity_def_parser.parse(ent_data.name)

    # Read component entities
    assets_ent_c_data: dict[str, DefClassData] = {}
    entity_def_parser_for_components: EntityDefParser = EntityDefParser(
        settings.ENTITY_DEFS_COMPONENT_DIR
    )
    for filename in os.listdir(settings.ENTITY_DEFS_COMPONENT_DIR):
        if filename.endswith(".def") and filename[0].isupper():
            comp_name: str = filename.rsplit(".", 1)[0]
            assets_ent_c_data[comp_name] = entity_def_parser_for_components.parse(
                comp_name
            )

    # Generate entity descriptions
    if settings.GAME_GENERATED_CLIENT_API_DIR.exists():
        shutil.rmtree(settings.GAME_GENERATED_CLIENT_API_DIR)
    settings.GAME_GENERATED_CLIENT_API_DIR.mkdir(parents=True)
    with (settings.GAME_GENERATED_CLIENT_API_DIR / "__init__.py").open("w") as fh:
        fh.write(
            f'"""The package contains generated python code for '
            f'the KBEngine client.\n\nGenerated by the "enki" '
            f'project <{settings.PROJECT_SITE}>\n"""\n\n'
        )
        fh.write(
            "from . import deftype, eserializer, kbenginexml, gameentity, description\n"
        )

    if settings.INCLUDE_MSGES:
        cmd = ImportClientMessagesCommand(login_name, password, loginapp_addr)
        res = await cmd.execute()
        if not res.success:
            logger.error(
                "The messages from Loginapp cannot be requested (err = '%s')",
                res.text,
            )
            sys.exit(1)
        assert res.result is not None

        code_generator = MessagesCodeGen(settings.CodeGenDstPath.APP)
        # TODO: [2025-08-27 19:32 burov_alexey@mail.ru]:
        # Начинка плагина не должна лезть в парсер
        code_generator.generate(
            client_msg_specs=res.result.client_msg_specs,
            loginapp_msg_specs=res.result.loginapp_msg_specs,
            baseapp_msg_specs=res.result.baseapp_msg_specs,
        )

    if settings.INCLUDE_ERRORS:
        error_dst_path = settings.CodeGenDstPath.SERVERERROR
        err_descr_cmd = ImportServerErrorsDescrCommand(loginapp_addr)
        err_descr_res = await err_descr_cmd.execute()
        if not err_descr_res.success:
            logger.error(
                "The messages from Loginapp cannot be requested (err = '%s')",
                err_descr_res.text,
            )
            sys.exit(1)
        assert err_descr_res.result is not None

        error_code_gen = ErrorCodeGen(error_dst_path)
        error_code_gen.generate(err_descr_res.result.descrs)

    # Generate entity descriptions
    type_dst_path = settings.CodeGenDstPath.TYPE
    entity_dst_path = settings.CodeGenDstPath.ENTITY
    eserialier_dst_path = settings.CodeGenDstPath.SERIALIZER_ENTITY

    importClientEntityDef_cmd = ImportClientEntityDefCommand(  # noqa: N806
        login_name, password, loginapp_addr
    )
    importClientEntityDef_res = await importClientEntityDef_cmd.execute()  # noqa: N806
    if not importClientEntityDef_res.success:
        logger.error(
            "The messages from Loginapp cannot be requested (err = '%s')",
            importClientEntityDef_res.text,
        )
        sys.exit(1)
    assert importClientEntityDef_res.result is not None

    type_code_gen = TypesCodeGen(type_dst_path)
    type_code_gen.generate(importClientEntityDef_res.result.types)

    # Это нужно в процедуру (загрузка deftype)
    import importlib.util

    spec = importlib.util.spec_from_file_location(
        "deftype", settings.CodeGenDstPath.TYPE
    )
    assert spec is not None
    assert spec.loader is not None
    module: ModuleType = importlib.util.module_from_spec(spec)
    sys.modules["deftype"] = module
    spec.loader.exec_module(module)

    entity_code_gen = EntitiesCodeGen(entity_dst_path)
    entity_code_gen.generate(
        importClientEntityDef_res.result.entities,
        assets_ent_data,
        assets_ent_c_data,
        module,
    )

    eserializer_code_gen = EntitySerializersCodeGen(eserialier_dst_path)
    eserializer_code_gen.generate(
        importClientEntityDef_res.result.entities,
        assets_ent_data,
        assets_ent_c_data,
        module,
    )

    # Generate data of kbengine.xml
    logger.info(
        f"Generate settings from kbengine.xml ... (to "
        f'"{settings.CodeGenDstPath.KBENGINE_XML}")'
    )
    data = KBEngineXMLParser(settings.KBENGINE_XML_PATH).parse()
    code_gen = KBEngineXMLDataCodeGen(settings.CodeGenDstPath.KBENGINE_XML)
    code_gen.generate(data)


async def main() -> None:
    """Точка входа для запуска скрипта."""
    log.setup_root_logger(logging.getLevelName(settings.LOG_LEVEL))

    env = Env()
    got_error = False
    try:
        game_account_name = env.str("GAME_ACCOUNT_NAME")
    except EnvError as err:
        got_error = True
        logger.error(err)
    try:
        game_password = env.str("GAME_PASSWORD")
    except EnvError as err:
        got_error = True
        logger.error(err)
    try:
        kbe_loginapp_host = env.str("KBE_LOGINAPP_HOST")
    except EnvError as err:
        got_error = True
        logger.warning(err)
    try:
        kbe_loginapp_tcp_port = env.int("KBE_LOGINAPP_TCP_PORT")
    except EnvError as err:
        got_error = True
        logger.warning(err)

    if got_error:
        logger.error("Failed to load environment variables")
        sys.exit(1)

    await generate_code(
        game_account_name,  # pyright: ignore[reportPossiblyUnboundVariable]
        game_password,  # pyright: ignore[reportPossiblyUnboundVariable]
        Addr(kbe_loginapp_host, Port(kbe_loginapp_tcp_port)),  # pyright: ignore[reportPossiblyUnboundVariable]
    )


if __name__ == "__main__":
    asyncio.run(main())
